# -*- coding: utf-8 -*-
"""PYTHON PROGRAMS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ca1kgAf7WZc13e-ulXIOIHSqaP4urtlN
"""

# Program 1: Hardcoding Variables

x = 15
y = 25

result = x * y
print("Multiplication of x and y is:", result)

# Program 2: Keyboard Input

try:
    number = int(input("Enter a number: "))
    print("Cube of the number is:", number ** 3)

except ValueError:
    print("Invalid input! Please enter an integer.")

with open("single_input.txt", "w") as file:
    file.write("8")

# Program 3: Read single input from file

try:
    with open("single_input.txt", "r") as file:
        value = int(file.read())

    print("Value from file:", value)
    print("Double of the value:", value * 2)

except FileNotFoundError:
    print("File not found")
except ValueError:
    print("Invalid data in file")

with open("multiple_inputs.txt", "w") as file:
    file.write("5\n15\n25\n35")

# Program 4: Read multiple inputs from file

try:
    with open("multiple_inputs.txt", "r") as file:
        values = file.readlines()

    total = 0
    for v in values:
        total += int(v.strip())

    print("Values read from file:", values)
    print("Total sum:", total)

except FileNotFoundError:
    print("File not found")
except ValueError:
    print("Non-numeric value found in file")

# Program 5: Debugging and Error Handling

try:
    file_name = input("Enter the file name to open: ")
    with open(file_name, "r") as file:
        data = file.read()
        print("File data:")
        print(data)

except FileNotFoundError:
    print("Error: The specified file was not found.")
except Exception as error:
    print("Some error occurred:", error)

# Program 6 Check Even or Odd
num = int(input("Enter a number: "))

if num % 2 == 0:
    print("Even number")
else:
    print("Odd number")

# Program 7 Find Largest of Two Numbers
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

if a > b:
    print("Largest number is:", a)
else:
    print("Largest number is:", b)

# Program 8 Factorial of a Number
num = int(input("Enter a number: "))
fact = 1

for i in range(1, num + 1):
    fact = fact * i

print("Factorial is:", fact)

# Program 9 Fibonacci Series
n = int(input("Enter number of terms: "))

a, b = 0, 1
print(a, b, end=" ")

for i in range(2, n):
    c = a + b
    print(c, end=" ")
    a, b = b, c

# Program 10 Prime Number Check
num = int(input("Enter a number: "))
flag = True

if num <= 1:
    flag = False
else:
    for i in range(2, num):
        if num % i == 0:
            flag = False
            break

if flag:
    print("Prime number")
else:
    print("Not a prime number")

# Program 11 Reverse a Number
num = int(input("Enter a number: "))
rev = 0

while num > 0:
    digit = num % 10
    rev = rev * 10 + digit
    num //= 10

print("Reversed number:", rev)

# Program 12 Sum of Elements in a List
numbers = [10, 20, 30, 40]
total = 0

for n in numbers:
    total += n

print("Sum of list elements:", total)

# Program 13 Palindrome Check (String)
text = input("Enter a word: ")

if text == text[::-1]:
    print("Palindrome")
else:
    print("Not a palindrome")

# Program 14 Count Vowels in a String
text = input("Enter a sentence: ")
count = 0

for ch in text:
    if ch.lower() in "aeiou":
        count += 1

print("Number of vowels:", count)

# Program 15 Simple Calculator
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)